### ISSUE TITLE
use `.env` files for sensitive information

### ISSUE THREAD

**Issue by tweak-wtf** [nicoloboschi/poetry-dockerize-plugin#34]
hey there ✌️ 
first of all thanks for that plugin... really makes some of my development much easier ❤️ 

is it possible to refer to a local `.env` file in the `pyproject.toml` in order to prevent sensitive information (API keys, passwords, that kinda stuff) from ending up in git history?

rn i'm just tracking a `pyproject.toml.example` and ignore the actual one.

**Comment by nicoloboschi** [comment]
Hey @tweak-wtf this is now released with 1.2.0 

See the doc here: https://github.com/nicoloboschi/poetry-dockerize-plugin?tab=readme-ov-file#configuration-via-environment-variables

Thanks for reporting!

**Comment by tweak-wtf** [comment]
great stuff! thanks for implementing this so quickly 🚀
